version: 2.1

orbs:
  windows: circleci/windows@2.2.0

jobs:
  test:
    description: Setup and run application tests
    executor:
      name: windows/default
    steps:
      - checkout
      - run:
          name: "Install project dependencies"
          command: MSBuild.exe HelloWorld.csproj  /t:Rebuild /p:DeployOnBuild=true /p:Configuration=Release  /p:SkipPostSharp=true
  
workflows:
  test_and_build:
    jobs:
      - test
      - build:
          requires:
            - test

                     
