version: 2.1

orbs:
  windows: circleci/windows@2.2.0

jobs:
  test:
    description: Setup and run application tests
    executor:
      name: windows/default
    steps:
      - checkout
     
      - run:
          name: "Install project dependencies"
          command: nuget restore
      - run:
          name: "Install project dependencies"
          working_directory: /temp/workspace/
          command: new-item -ItemType File kan.txt
          # Msbuild.exe HelloWorld.csproj -t:restore /t:Build
           #MSBuild.exe HelloWorld.csproj  /t:Rebuild /p:DeployOnBuild=true /p:Configuration=Release  /p:SkipPostSharp=true
      - run:
          name: "Install project dependencies"
          working_directory: /temp/workspace/
          command: echo "hello"| Add-Content .\kan.txt
      - persist_to_workspace:
          root: C:\temp\workspace\
          paths:
            - .
           
  deploy:
    docker:
    - image: mcr.microsoft.com/dotnet/core/sdk
    description: Build application with Release configuration
    steps:     
      - attach_workspace:
          at: ~/repo/artifact/
      - run:
          name: Installing deployment dependencies
          working_directory: ~/repo/aritifact/
          command: |
            ls
      - run:
          name: Installing deployment dependencies
          working_directory: ~/repo
          command: |
            apt-get -y -qq update
            apt-get install -y python-pip python-dev build-essential
            pip install  --upgrade setuptools
            pip install  awsebcli --upgrade
      - run:
          name: Create AWS credentials manually
          command: |
            mkdir ~/repo/artifact/.aws
            touch ~/repo/artifact/.aws/config
            chmod 600 ~/repo/artifact/.aws/config
            echo "[profile kenani]" > ~/repo/artifact/.aws/config
            echo "aws_access_key_id=$AWS_ACCESS_KEY_ID" >> ~/repo/artifact/.aws/config
            echo "aws_secret_access_key=$AWS_SECRET_ACCESS_KEY" >> ~/repo/artifact/.aws/config
      - run:
          name: Deploy to EB if branch is Master
          working_directory: ~/repo/artifact
          command: |
            eb init --region us-east-1 --platform iis-10.0 circleci-beanstalk 
            eb deploy circleci-beanstalk-dev
            # eb create circleci-beanstalk-dev
workflows:
  test_and_build:
    jobs:
      - test
      - deploy:
          requires:
            - test
      

                     
